Repository Parallel-Gaming-Studio/WordFlight, pull requests merged in 2020-05, with the labels that each got.

#99 Small Updates
  README.md
  docs/images/end_scene/.htaccess
  docs/images/end_scene/old/.htaccess
  docs/images/leaderboard_scene/.htaccess
  docs/images/leaderboard_scene/old/.htaccess
  docs/images/old/.htaccess
  docs/images/old/concept_end_scene.png
  docs/images/old/concept_leaderboard_scene.png
  docs/images/old/concept_play_scene.png
  docs/images/old/concept_start_scene.png
  docs/images/play_scene/.htaccess
  docs/images/play_scene/old/.htaccess
  docs/images/sponsors/.htaccess
  docs/images/sponsors/logos_black/.htaccess
  docs/images/sponsors/logos_white/.htaccess
  docs/images/start_scene/.htaccess
  docs/images/start_scene/old/.htaccess
  docs/includes/.database/.htaccess
  docs/includes/.database/WordFlight_Build_Database.sql
  docs/includes/.database/WordFlight_INSERT_Leaderboard.sql
  docs/includes/.database/WordFlight_INSERT_Player_Into_Leaderboard.sql
  docs/includes/.database/WordFlight_INSERT_Sponsors.sql
  docs/includes/.database/WordFlight_INSERT_Words.sql
  docs/includes/.database/WordFlight_SELECT_All_Tables.sql
  docs/includes/.database/WordFlight_SELECT_Leaderboard_Top_7.sql
  docs/includes/.database/WordFlight_SELECT_Random_Word_Sponsor.sql
  docs/includes/.database/dbo.WordFlightLeaderboard.sql
  docs/includes/.database/dbo.WordFlightSponsors.sql
  docs/includes/.database/dbo.WordFlightWords.sql
  docs/scripts/.htaccess
  docs/scripts/jquery-ui-1.12.1/.htaccess
  docs/scripts/jquery-ui-1.12.1/_notes/.htaccess
  docs/scripts/jquery-ui-1.12.1/external/.htaccess
  docs/scripts/jquery-ui-1.12.1/external/jquery/.htaccess
  docs/scripts/jquery-ui-1.12.1/external/jquery/_notes/.htaccess
  docs/scripts/jquery-ui-1.12.1/images/.htaccess
  docs/scripts/jquery-ui-1.12.1/images/_notes/.htaccess
Labels: documentation

#103 Phrase Spaces Update
  .gitignore
  docs/includes/.database/WordFlight_Build_Database.sql
  docs/includes/.database/WordFlight_INSERT_Words.sql
  docs/includes/.gitignore
  docs/includes/db_admin.php
  docs/scripts/game.js
  docs/scripts/loader.js
Labels: enhancement, testing needed

#104 Image Padding
  docs/scripts/game.js
Labels: testing needed

#105 Padding and Cleanup
  docs/scripts/game.js
Labels: testing complete, testing needed

#106 Sizing, Loading Sequence, and Structure
  docs/scripts/game.js
  docs/scripts/game_manager.js
  docs/scripts/loader.js
  docs/scripts/scene_end.js
  docs/scripts/scene_leaderboard.js
  docs/scripts/scene_play.js
  docs/scripts/scene_start.js
Labels: testing needed

#107 Difficulty Levels Overlay
  docs/includes/reusables.html
  docs/scripts/game.js
  docs/scripts/game_manager.js
  docs/styles/styles.css
Labels: testing needed

#108 Added difficulty functionality
  docs/scripts/game.js
  docs/scripts/word_generator.php
Labels: enhancement, testing needed

#109 Difficulty Select Overlay
  docs/scripts/game.js
  docs/scripts/scene_start.js
  docs/styles/styles.css
Labels: enhancement, testing needed

#111 Patch jQuery Vulnerability
  docs/index.html
  docs/scripts/jquery-3.4.1.min.js
  docs/scripts/jquery-3.5.1.js
  docs/scripts/jquery-3.5.1.min.js
  docs/scripts/jquery.js
  docs/scripts/jquery_activity.js
  docs/scripts/jquery_nav.js
Labels: bug

#112 Test branch
  .gitignore
  docs/includes/.database/WordFlight_Build_Database.sql
  docs/includes/.database/WordFlight_INSERT_Words.sql
  docs/includes/.gitignore
  docs/includes/db_admin.php
  docs/includes/reusables.html
  docs/index.html
  docs/scripts/game.js
  docs/scripts/game_manager.js
  docs/scripts/jquery-3.4.1.min.js
  docs/scripts/jquery-3.5.1.js
  docs/scripts/jquery-3.5.1.min.js
  docs/scripts/jquery.js
  docs/scripts/jquery_activity.js
  docs/scripts/jquery_nav.js
  docs/scripts/loader.js
  docs/scripts/scene_end.js
  docs/scripts/scene_leaderboard.js
  docs/scripts/scene_play.js
  docs/scripts/scene_start.js
  docs/scripts/word_generator.php
  docs/styles/styles.css
Labels: bug, enhancement, testing needed

#113 small Game.js update
  docs/scripts/game.js
  docs/scripts/word_generator.php
Labels: testing complete, testing needed

#114 Tutorial Overlay
  docs/images/WordFlight_PlayScene_TutorialOverlay2.PNG
  docs/images/WordFlight_TutorialOverlay.PNG
  docs/includes/reusables.html
  docs/scripts/game.js
  docs/scripts/game_manager.js
  docs/styles/styles.css
Labels: testing complete, testing needed

#115 Tutorial Overlay Update
  docs/400.html
  docs/401.html
  docs/403.html
  docs/404.html
  docs/500.html
  docs/includes/play_scene.html
  docs/scripts/game.js
  docs/scripts/game_manager.js
  docs/scripts/scene_leaderboard.js
  docs/scripts/scene_play.js
  docs/styles/styles.css
Labels: testing needed

#116 Test branch
  docs/400.html
  docs/401.html
  docs/403.html
  docs/404.html
  docs/500.html
  docs/images/WordFlight_PlayScene_TutorialOverlay2.PNG
  docs/images/WordFlight_TutorialOverlay.PNG
  docs/includes/play_scene.html
  docs/includes/reusables.html
  docs/scripts/game.js
  docs/scripts/game_manager.js
  docs/scripts/scene_leaderboard.js
  docs/scripts/scene_play.js
  docs/scripts/word_generator.php
  docs/styles/styles.css
Labels: enhancement

#117 Fixed Tutorial X Button
  docs/scripts/game.js
Labels: bug, testing needed

#118 Tutorial Overlay Images
  docs/images/WordFlight_PlayScene_TutorialOverlay2.PNG
  docs/images/WordFlight_TutorialOverlay.PNG
  docs/images/WordFlight_TutorialOverlay2.PNG
  docs/images/WordFlight_TutorialOverlay3.png
  docs/images/WordFlight_TutorialOverlay4.png
  docs/includes/reusables.html
  docs/styles/styles.css
Labels: bug, testing needed

#119 Tutorial Overlay Improvements
  docs/images/WordFlight_PlayScene_TutorialOverlay2.PNG
  docs/images/WordFlight_TutorialOverlay.PNG
  docs/images/WordFlight_TutorialOverlay2.PNG
  docs/images/WordFlight_TutorialOverlay3.png
  docs/images/WordFlight_TutorialOverlay4.png
  docs/includes/reusables.html
  docs/scripts/game.js
  docs/styles/styles.css
Labels: enhancement, testing needed

#120 Tutorial Overlay Update
  docs/includes/reusables.html
  docs/styles/styles.css
Labels: enhancement, testing needed

#121 Difficulty Overlay Update
  docs/scripts/game.js
  docs/styles/styles.css
Labels: enhancement, testing needed

#122 Overlay Updates
  docs/includes/reusables.html
  docs/scripts/game.js
  docs/styles/styles.css
Labels: enhancement, testing needed

#123 Final Client Requests
  docs/includes/.database/WordFlight_Build_Database.sql
  docs/includes/.database/WordFlight_INSERT_Words.sql
  docs/scripts/game.js
  docs/scripts/game_manager.js
  docs/scripts/scene_end.js
  docs/scripts/scene_leaderboard.js
  docs/scripts/word_generator.php
  docs/styles/styles.css
Labels: enhancement, testing needed

#124 Final Client Requests
  docs/includes/.database/WordFlight_Build_Database.sql
  docs/includes/.database/WordFlight_INSERT_Words.sql
  docs/includes/reusables.html
  docs/scripts/game_manager.js
  docs/scripts/scene_end.js
  docs/scripts/scene_leaderboard.js
  docs/styles/styles.css
Labels: enhancement

#125 Update reusables.html
  docs/includes/reusables.html
Labels: bug, enhancement
